### ISSUE TITLE
Can't have more then one highlighted field reliably.  Sometimes two work but return intermittent errors.  Anything more does not work at all.

### ISSUE THREAD

**Issue by zergormagn** [typesense/typesense-autocomplete-demo#1]
## Description

Can't have more then one highlighted field reliably.  Sometimes two work but return intermittent errors.  Anything more does not work at all.

## Steps to reproduce
set 
`highlight_full_fields: 'name, description'`
and try something like 
                            `const html_fragment = html`${item.highlights.find(h => h.field === 'description').value}``

**Comment by jasonbosco** [comment]
> Sometimes two work but return intermittent errors.

May I know what error is thrown?

**Comment by zergormagn** [comment]
error is:
`Uncaught TypeError: Cannot read properties of undefined (reading 'value')`
on line:
`const html_fragment = html${item.highlights.find(h => h.field === 'description').value}`
you can get this error when increasing the number of fields in query_by too.

**Comment by jasonbosco** [comment]
The issue is that not all fields might have highlights for every search term. 

I've pushed out an update to account for this: https://github.com/typesense/typesense-autocomplete-demo/commit/caf732d6921507a2748656db1e2be0989e6e6f74
