### ISSUE TITLE
Specify Version in the included JS libraries

### ISSUE THREAD

**Issue by zergormagn** [typesense/typesense-autocomplete-demo#2]
## Description
Currently it's difficult to see the version of the included code. For autocomplete.js the version is specified on top of the JS file:
@algolia/autocomplete-js 1.7.4 
but there is no version for the type sense library:
https://cdn.jsdelivr.net/npm/typesense@1/dist/typesense.min.js

**Comment by jasonbosco** [comment]
Notice `typesense@1` in the URL - that `@1` is the version number for typesense-js. 

You can change that to a more specific version like this: 

```
https://cdn.jsdelivr.net/npm/typesense@1.4.4/dist/typesense.min.js
```
